name: compile_target

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: checkout commit
        uses: actions/checkout@v4
      - name: Get version
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./test/requirements.txt
      - name: Run testing script
        run: |
          python3 ./test/test_target.py ${{ env.RELEASE_VERSION }}
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: test_report
          path: test/test_report.txt
