name: compile_target

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      # clone the unlogged-sdk project
      - name: checkout commit
        uses: actions/checkout@v4

      # unlogged-sdk project
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Get version
        run: |
          echo "$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      # Testing script
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./test/requirements.txt
      - name: Run testing script
        run: |
          python3 ./test/test_target.py ${{ env.RELEASE_VERSION }}

      # report upload
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: test_report
          path: test/test_report.txt
      