name: compile_target

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['8','11', '17', '21' ]

    steps:
      # clone the unlogged-sdk project
      - name: checkout commit
        uses: actions/checkout@v4

      # unlogged-sdk project
      # setting JDK to 11 in case of java 8 project. For other projects JDK is set to project JDK
      - name: Set up JDK ${{ matrix.java-version == '8' && '11' || matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version == '8' && '11' || matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Get version
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      # Testing script
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/test/python/requirements.txt
      - name: Run testing script
        run: |
          python3 ./src/test/python/compile_target.py ${{ env.RELEASE_VERSION }} ${{ matrix.java-version }}
